### ISSUE TITLE
I can't register

### ISSUE THREAD

**Issue by Dr-Bamboo-Dev** [PACHI-DEV/rhythm-mmo#1]
It just tells me, "Connection failed, trying again"

**Comment by PACHI-DEV** [comment]
Hi! The server is down currently due to some SSL changes I was making. I'll let you know when it's up again.

**Comment by PACHI-DEV** [comment]
@Tagwart It's back up! I sort of messed up the older prod version that was running, so the game looks as it looks in my dev build right now. I'm undergoing a major graphics overhaul, so some things might be a little weird, and I've disabled visible equips for now. Enjoy!

https://gotm.io/pachidev/rhythm-mmo

**Comment by Dr-Bamboo-Dev** [comment]
I tried again to day, and it still won't connect. Sorry I didn't get around to trying it sooner.

**Comment by PACHI-DEV** [comment]
@Tagwart There seems to be an issue with registration, I’ll look into it. You can join the discord for updates if you’d like: https://discord.gg/NW24U9h 
In #rmmo-discussion
